version: "3"
services:
  nginx:
    image: nginx:1.27.3
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./public/:/var/www/html/
  php:
    image: php:8.2-fpm
    networks:
      - internal
    volumes:
      - ./public/:/var/www/html/
networks:
  internal:
    driver: bridge