version: "3.9"
services:
  nginx:
    build: ./nginx/
    image: nginx:1.27.3
    ports:
      - 80:80
    volumes:
      - ./public/:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  php:
    image: php:8.2-fpm
    build: ./public/
    expose:
      - 9000
    volumes:
      - ./public/:/var/www/html