version: "3.9"
services:
  nginx:
    image: nginx:1.27.3
    build: ./nginx/
    ports:
    - 80:80

    volumes:
      - ./public/:/var/www/html/
      - ./logs:/var/log/nginx

  php:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    expose:
      - 9000
    volumes:
      - ./public/:/var/www/html/