version: "3.9"
services:
  nginx:
    #build: ./nginx/
    image: nginx:1.27.3
    ports:
      - 80:80
    volumes:
      - ./public/:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
  php:
    image: php:8.2-fpm
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - 9000
    volumes:
      - ./:/var/www/
      - ./public/:/var/www/html
      # - ./composer.json:/var/www/composer.json
      #- ./src/:/var/www/src
      #- ./vendor/:/var/www/vendor
  mysql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=betting
      - MYSQL_USER=betting
      - MYSQL_PASSWORD=betting
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
      - './dump.sql:/docker-entrypoint-initdb.d/dump.sql'