version: "3.9"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - 80:80
    volumes:
      - ./public/:/var/www/html
  php:
    image: php:8.2-fpm
    build: ./public/
    expose:
      - "9000"
    volumes:
      - ./public/:/var/www/html