version: '3'
services:
  php:
    image: php:8.2-fpm
    volumes:
      - './public:/var/www/html'
  
  nginx:
    image: nginx:1.27.3
    ports:
      - 80:80
    volumes:
      - './public:/var/www/html'
      - './docker/nginx/conf.d/:/etc/nginx/conf.d'

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "betting"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - 3306:3306