version: "3.9"
services:
  nginx:
    image: nginx:1.27.3
    #build: ./docker/nginx/
    ports:
    - 80:80

    volumes:
      - ./public/:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs:/var/log/nginx

  php:
    image: php:8.2-fpm
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    expose:
      - 9000
    volumes:
      - ./public/:/var/www/html/